id: P1794ED04
initial_creation_type: input
source_metadata:
  title: Alak Zenkar Rinpoche
  language: nl
  description: 'Texts by and about the great scholar Alak Zenkar Rinpoche Thupten
    Nyima (a lags gzan dkar thub bstan nyi ma, b.1943):'
  volume:
    a15bb526c4694495927866574c27f6a2:
      title: Biography of Jamgön Kongtrul Lodrö Thaye
      parent: Biography
    e491b76e9b6b4acc8c6cfaa5d0a348e5:
      title: Biography of Jamyang Khyentse Wangpo
      parent: Biography
    a3fb6efb960848f5b7c326f205ed2e5c:
      title: Biography of Patrul Rinpoche
      parent: Biography
    8ff6826f50df41eca00e405206163187:
      title: Biography of Shechen Gyaltsab Gyurme Pema Namgyal
      parent: Biography
    2b01c430cbe04fed950ee20ef37aea77:
      title: Brief Biography of Drakkar Lobzang Palden
      parent: Biography
    b8c961a2173b45e9b52ee1fab67ca9ea:
      title: Brief Biography of Kharlek Tulku Pema Kunzang Rangdrol
      parent: Biography
    075f0b079afb497981525d015c20cb0f:
      title: Brief Biography of Tāranātha
      parent: Biography
    79dc8d8b98d64cca86931643cf19a26c:
      title: A Brief Presentation of the Nine Vehicles
      parent: Buddhist Philosophy
    3a7a30915a214c0b849669b5c97033f3:
      title: Long Life Prayer for Alak Zenkar Rinpoche
      parent: Long Life Prayers
    cbff3a2937a24bf58ffe6e829e5222e4:
      title: Long Life Prayer for Patrick Gaffney (Yeshé Wangyal)
      parent: Long Life Prayers
    d60f2794577d494f839c38d9a36867a0:
      title: Prayer for the Long Life of Alak Zenkar Rinpoche, the Incarnation of
        Do Khyentsé Yeshé Dorjé
      parent: Long Life Prayers
    fb5deaae1b5c4998a597754102ff894f:
      title: 'Bodhicaryāvatāra: Teachings and Overview'
      parent: Oral Teachings
    dd7d8d0a674440b08364dcfc98a3e960:
      title: Light from the Wisdom Sun
      parent: Prayers and Practices
    34f7a1e949364b99831df260992c0a02:
      title: A Prayer for the Swift Rebirth of Tenpai Nyima Rinpoche
      parent: Swift Rebirth Prayers
    8f474bd4a9934f6f8625b4c8b267ba22:
      title: Prayer for Swift Rebirth of the Fourth Dodrupchen Rinpoche
      parent: Swift Rebirth Prayers
created_at: '2022-02-28T22:37:59.747164'
last_modified_at: '2022-02-28T22:37:59.747166'
